version: "3"
services:
  postgres:
    image: "postgres:15.3"
    port:
      - "5432:5432"
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: mydb
